In [ ]:
# Tensors: Tensor is a data structure multi dimensional array designed for mathematical and computational efficiency
# O dimensional tensors: Scalar 1,2,3,4,5
# Vectors: 1 dimensional tensor (a list of numbers)
# Matrices: 2-dimensional tensors (grayscale image)
# 3D tensors: coloured images (rgb)
# 4D tensor: Batches of RGB image
# 5D tensor: Video data
# Why are tensors useful?
# -> Mathematical Operations
# -> Representation of real-world data
# -> Efficient Computations
# Where are Tensors used in Deep Learning?
# -> Data Storage
# -> Weights and Biases
# -> Matrix Operations
# -> Training Process

In [18]:
import torch
torch.__version__

'2.13.0+cpu'

In [19]:
if torch.cuda.is_available():
    print("GPU is available")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU")

GPU not available. Using CPU


In [5]:
# Creating a Tensor
torch.empty(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
torch.zeros(4,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [7]:
torch.ones(1,2)

tensor([[1., 1.]])

In [9]:
torch.rand(2,3)

tensor([[0.2727, 0.4865, 0.8991],
        [0.0227, 0.4971, 0.3174]])

In [10]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [11]:
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [12]:
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [14]:
torch.linspace(0,-10,10)

tensor([  0.0000,  -1.1111,  -2.2222,  -3.3333,  -4.4444,  -5.5556,  -6.6667,
         -7.7778,  -8.8889, -10.0000])

In [15]:
torch.eye(2,2)

tensor([[1., 0.],
        [0., 1.]])

In [16]:
torch.full((3,3),6)

tensor([[6, 6, 6],
        [6, 6, 6],
        [6, 6, 6]])

In [22]:
# Tensor Shapes
x=torch.tensor([[1,2,3],[6,7,8]])

In [23]:
x.shape

torch.Size([2, 3])

In [24]:
torch.empty_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [25]:
#Tensor Data Type
x.dtype

torch.int64